### ISSUE TITLE
Verbose flag/level for reading fields

### ISSUE THREAD

**Issue by gfngoncalves** [fluiddyn/fluidfoam#28]
For integration with other packages, it would be good if the functions on `readof.py` could receive an optional argument that would turn off the non-essential messages (e.g. "Reading file ..."). The default value could be set to True (or 1, if the preference is for verbosity levels) if backwards compatibility is essential.

I can prepare a PR if there is interest in the feature.

**Comment by CyrilleBonamy** [comment]
Hello,
I think this is a good idea.
Feel free to suggest a PR :-)
We will merge it as soon as possible.
Cyrille

**Comment by gfngoncalves** [comment]
I have a first implementation in my fork. Regarding warnings such as `print(R+"Warning : No data on boundary/patch")`, do you think these should these be supressed according to the verbose flag as well? Or should they be changed to use `warnings.warn` maybe, so they can be filtered by the user?

**Comment by CyrilleBonamy** [comment]
I think we can supress these warnings according to the verbose flag. 👍

**Comment by CyrilleBonamy** [comment]
thank very much for your contribution #33  👍
