### ISSUE TITLE
[Meta]: Adding releases to the Github repository

### ISSUE THREAD

**Issue by OpenFoam-User** [fluiddyn/fluidfoam#34]
Hello,
This is a meta question related to this repository. I think it would be very nice if releases added to the repository. This is useful because any user watching the repository could get notifications when a new release of `fluidfoam` is available.

Best regards

**Comment by CyrilleBonamy** [comment]
Yes, you are right!
I just updated the continuous integration (Github action) to push the pypi package at each "version" update.
And so I propose to add a new version at each version bump.

The next version will be very soon: when we will close your issues. 👍

**Comment by CyrilleBonamy** [comment]
Done :-)
