### ISSUE TITLE
Scipy version

### ISSUE THREAD

**Issue by OpenFoam-User** [fluiddyn/fluidfoam#37]
Hello,
In `setup.py` the scipy version is set to `scipy==1.7.3`.  At the time of writing, the latest version of `scipy` is `1.8.0`.

Is there a reason to restrict the version of scipy? why not using `scipy>=1.7.3` for example?

Thank you

**Comment by CyrilleBonamy** [comment]
Hello,
I am not sure but i have the feeling that scipy 1.8.0 has some issues with python 3.7....
Specifically if i set >=1.7.3 i get the following error with readthedoc : https://readthedocs.org/projects/fluidfoam/builds/16599256/

Maybe you have some suggestions?

Cyrille

**Comment by OpenFoam-User** [comment]
Hi,
You're right, scipy 1.8 supports only Python 3.8+
Are there any Linux LTS distribution that still use Python 3.7?

Anyway, I think it's still a good reason to support Python 3.7.

Thanks
