### ISSUE TITLE
handling multiple regions

### ISSUE THREAD

**Issue by fab6** [fluiddyn/fluidfoam#50]
Hi,
It would be great, if multi-region cases can be handled in fluidfoam as well.
E.g. I would like to read scalar values from the different regions for the multiRegionHeater case, which has 5 regions (with non-moving fixed mesh)? 
Thank you in advance!
Fab

**Comment by CyrilleBonamy** [comment]
Hi
I developed very quickly the support for regions/sets.
Can you test with the fluidfoam of my fork : https://github.com/CyrilleBonamy/fluidfoam/ ?
If you have difficulties to install fluidfoam from my fork, don't hesitate to contact me :-)

Example to use (to read pressure field and associated mesh) : 
p = fluidfoam.readfield(path='.', region="bottomWater", name="p", time_name="50")
x, y, z = fluidfoam.readmesh(path='.', region="bottomWater")

**Comment by fab6** [comment]
Hi,
thanks, it works almost for my case:
![image](https://github.com/fluiddyn/fluidfoam/assets/3047695/b4aab7cb-d8a1-46f9-929e-4e456e1fcee0)
Temperature is read from the regions, though its looking for a sets field, which is not always available.

I used a slight adjustment
```
import fluidfoam 
T = fluidfoam.readfield(path='../', region="rightRoom", name="T", time_name="50")
print(T)
print(T.max())
T = fluidfoam.readfield(path='../', region="rightWall", name="T", time_name="50")
print(T)
print(T.max())
x, y, z = fluidfoam.readmesh(path='../', region="rightWall")
x, y, z = fluidfoam.readmesh(path='../', region="rightRoom")
```
Thank you very much!

**Comment by CyrilleBonamy** [comment]
I am not sure I understand your point  about the "sets" field not always being available. Do you have an exemple of such case ?

**Comment by CyrilleBonamy** [comment]
Done #51  :-)
Enjoy

**Comment by fab6** [comment]
Thank you!
