### ISSUE TITLE
parsing failure for binary boundary data

### ISSUE THREAD

**Issue by kahilah** [fluiddyn/fluidfoam#60]
Hi,

I had a dataset which happened to have "}". ")" byte strings within the nonuniform binary data block for the patch. Such a happenstance leads to an unexpected exit of parsing in `_parse_session(self, title)` function, yielding later exceptions as well.

Unfortunately I was not able to reproduce the problem in any simple data sets I have available but still wanted to share the behavior here.

**Comment by CyrilleBonamy** [comment]
Hello @kahilah 
Thank you for your interest in fluidfoam and for opening this issue.
Is it possible to have an example file (even a large one) to reproduce the problem?
Thank you

**Comment by kahilah** [comment]
Hi,
I handcrafted a file including a boundary patch which fails with error
`TypeError: 'bytes' object does not support item assignment
`

File attached

[Urandomised.tar.gz](https://github.com/user-attachments/files/17011657/Urandomised.tar.gz)

**Comment by CyrilleBonamy** [comment]
Thank you again for your interest.
The bug is resolved with #61
